[package]
name = "metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
nix.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
settings.workspace = true
